<script lang="ts">
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';

	let isLoading = true;

	onMount(async () => {
		try {
			const response = await fetch('/api/auth/me');
			const data = await response.json();
			if (data.success) {
				goto('/dashboard');
				return;
			}
		} catch (error) {
			// User not logged in, show landing page
		} finally {
			isLoading = false;
		}
	});
</script>

<svelte:head>
	<title>Quilty - AI-Powered Screenplay Analysis</title>
	<meta name="description" content="Professional screenplay analysis powered by Claude Opus 4.1 and Grok 4. Get detailed feedback, Hollywood poster concepts, and industry insights." />
</svelte:head>

{#if isLoading}
	<div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-slate-900 via-blue-900 to-slate-900">
		<div class="text-center">
			<div class="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-400 mx-auto mb-4"></div>
			<p class="text-blue-200">Loading...</p>
		</div>
	</div>
{:else}
	<div class="relative bg-gradient-to-br from-slate-900 via-blue-900 to-slate-900 overflow-hidden min-h-screen">
		<!-- Background effects -->
		<div class="absolute inset-0 opacity-20">
			<div class="w-full h-full" style="background-image: url('data:image/svg+xml,<svg width=&quot;60&quot; height=&quot;60&quot; viewBox=&quot;0 0 60 60&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;><g fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;><g fill=&quot;%23ffffff&quot; fill-opacity=&quot;0.02&quot;><circle cx=&quot;30&quot; cy=&quot;30&quot; r=&quot;2&quot;/></g></g></svg>');"></div>
		</div>
		
		<div class="max-w-7xl mx-auto relative z-10">
			<div class="lg:grid lg:grid-cols-12 lg:gap-8 min-h-screen">
				<!-- Content -->
				<div class="px-4 sm:px-6 lg:px-8 lg:col-span-7 flex items-center">
					<div class="max-w-2xl mx-auto lg:mx-0">
						<div class="text-center lg:text-left">
							<h1 class="text-5xl sm:text-6xl lg:text-7xl font-bold tracking-tight">
								<span class="block text-white mb-2">Professional</span>
								<span class="block bg-gradient-to-r from-blue-400 via-purple-400 to-yellow-400 bg-clip-text text-transparent">
									Screenplay
								</span>
								<span class="block bg-gradient-to-r from-yellow-400 via-orange-400 to-red-400 bg-clip-text text-transparent">
									Analysis
								</span>
							</h1>
							
							<p class="mt-6 text-xl text-blue-100 leading-relaxed">
								Powered by our <strong class="text-blue-300">Advanced Analysis Engine</strong>. 
								Get detailed feedback, Hollywood poster concepts, and comprehensive industry insights from multiple professional perspectives.
							</p>
							
							<div class="mt-8 flex flex-col sm:flex-row gap-4 justify-center lg:justify-start">
								<a
									href="/auth/register"
									class="btn-primary text-lg px-8 py-4 bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 transform hover:scale-105 transition-all duration-200 shadow-lg"
								>
									Start Analysis
								</a>
								<a
									href="/auth/login"
									class="inline-flex items-center justify-center px-8 py-4 border-2 border-blue-400 text-lg font-medium rounded-md text-blue-300 hover:bg-blue-400 hover:text-white transition-all duration-200"
								>
									Sign In
								</a>
							</div>
						</div>
					</div>
				</div>
				
				<!-- Hollywood Poster Preview -->
				<div class="lg:col-span-5 flex items-center justify-center p-8">
					<div class="relative">
						<div class="absolute inset-0 bg-gradient-to-r from-yellow-400 to-orange-500 rounded-2xl blur-xl opacity-30 transform rotate-6"></div>
						<div class="relative bg-gradient-to-b from-slate-800 to-slate-900 rounded-2xl p-8 border border-slate-700 shadow-2xl">
							<div class="text-center">
								<div class="w-24 h-32 mx-auto mb-6 bg-gradient-to-b from-yellow-400 to-orange-500 rounded-lg flex items-center justify-center shadow-lg">
									<span class="text-white text-4xl">🎬</span>
								</div>
								<h3 class="text-2xl font-bold text-white mb-2">AI-Generated</h3>
								<h4 class="text-xl font-semibold bg-gradient-to-r from-yellow-400 to-orange-400 bg-clip-text text-transparent mb-4">
									Movie Posters
								</h4>
								<p class="text-slate-300 text-sm leading-relaxed">
									Every screenplay analysis includes a Hollywood-quality poster concept generated by Grok 4, 
									giving you a visual representation of your story's cinematic potential.
								</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{/if}

<!-- Features Section -->
<div class="py-20 bg-gradient-to-b from-slate-50 to-white">
	<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
		<div class="text-center mb-16">
			<h2 class="text-4xl font-bold text-gray-900 mb-4">
				Powered by <span class="bg-gradient-to-r from-blue-600 via-purple-600 to-green-600 bg-clip-text text-transparent">Multi-Engine Analysis</span>
			</h2>
			<p class="text-xl text-gray-600 max-w-3xl mx-auto">
				Get the most comprehensive screenplay analysis with professional narrative expertise, 
				brutally honest industry insights, and commercial evaluation.
			</p>
		</div>

		<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-6">
			<div class="text-center group">
				<div class="w-16 h-16 mx-auto mb-4 bg-gradient-to-r from-blue-500 to-purple-500 rounded-2xl flex items-center justify-center group-hover:scale-110 transition-transform duration-200">
					<span class="text-white text-2xl">🎯</span>
				</div>
				<h3 class="text-lg font-semibold text-gray-900 mb-2">Craft Analysis</h3>
				<p class="text-gray-600 text-sm">Professional narrative structure, character development, and craft evaluation</p>
			</div>

			<div class="text-center group">
				<div class="w-16 h-16 mx-auto mb-4 bg-gradient-to-r from-purple-500 to-pink-500 rounded-2xl flex items-center justify-center group-hover:scale-110 transition-transform duration-200">
					<span class="text-white text-2xl">💀</span>
				</div>
				<h3 class="text-lg font-semibold text-gray-900 mb-2">Reality Check</h3>
				<p class="text-gray-600 text-sm">Cultural awareness and unfiltered industry feedback</p>
			</div>

			<div class="text-center group">
				<div class="w-16 h-16 mx-auto mb-4 bg-gradient-to-r from-green-500 to-emerald-500 rounded-2xl flex items-center justify-center group-hover:scale-110 transition-transform duration-200">
					<span class="text-white text-2xl">🏢</span>
				</div>
				<h3 class="text-lg font-semibold text-gray-900 mb-2">Commercial Intelligence</h3>
				<p class="text-gray-600 text-sm">Commercial viability, studio fit, and professional development insights</p>
			</div>

			<div class="text-center group">
				<div class="w-16 h-16 mx-auto mb-4 bg-gradient-to-r from-yellow-500 to-orange-500 rounded-2xl flex items-center justify-center group-hover:scale-110 transition-transform duration-200">
					<span class="text-white text-2xl">🎬</span>
				</div>
				<h3 class="text-lg font-semibold text-gray-900 mb-2">Movie Poster</h3>
				<p class="text-gray-600 text-sm">Professional Hollywood poster concept visualizing your story's potential</p>
			</div>

			<div class="text-center group">
				<div class="w-16 h-16 mx-auto mb-4 bg-gradient-to-r from-green-500 to-teal-500 rounded-2xl flex items-center justify-center group-hover:scale-110 transition-transform duration-200">
					<span class="text-white text-2xl">📊</span>
				</div>
				<h3 class="text-lg font-semibold text-gray-900 mb-2">Market Insights</h3>
				<p class="text-gray-600 text-sm">Commercial viability, target audience, and competitive landscape analysis</p>
			</div>
		</div>
	</div>
</div>
